DROP DATABASE IF EXISTS checks;
CREATE DATABASE checks;
USE checks;

-- EL CHECK INLINE SOLO PUEDE REFERIRSE A SU PROPIO ATRIBUTO
-- EL CHECK AL FINAL ME PERMITE RELACIONAR VARIOS ATRIBUTOS
CREATE TABLE checks(
  a INT CHECK (a>=3),
  b INT,
  c INT,
  CHECK (b<10),
  CHECK (a>C),
  CHECK (a<>B),
  -- PARA DAR UN NOMBRE AL CHECK
  CONSTRAINT chk_nombre CHECK(b > a AND b > c));
  
INSERT INTO checks VALUES (1,1,1);
  
