DROP DATABASE IF EXISTS TIENDA;
CREATE DATABASE TIENDA;
USE TIENDA;

CREATE TABLE FABRICANTE (
   CODIGO INT PRIMARY KEY,
   NOMBRE VARCHAR(100));
   
CREATE TABLE PRODUCTO (
   CODIGO INT PRIMARY KEY,
   NOMBRE VARCHAR(100),
   PRECIO DOUBLE,
   CODIGO_FABRICANTE INT,
   FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO)
   );
   
INSERT INTO FABRICANTE VALUES (50, 'INTEL');
INSERT INTO FABRICANTE VALUES (51, 'ASUS');

INSERT INTO PRODUCTO VALUES
(1, 'PROCESADOR i2000', 70.12, 50),
(2, 'PROCESADOR i98', 90.55, 50),
(3, 'PROCESADOR i24', 200.99, 50);
